version: "3"
services:
  server:
    image: staff-scheduling
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/staffscheduling?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=staffscheduling
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root

networks:
  springmysql-net: